### ISSUE TITLE
JPEG data may inadvertently have overly big size

### ISSUE THREAD

**Issue by morpheby** [YuriAndrianov/myApp-myAutoBudget#10]
https://github.com/YuriAndrianov/myApp-myAutoBudget/blob/2e9066c36ca5a0e57febb48d36d50c2f854b23b2/myAutoBudget/Helpers/ImageManager.swift#L17

Для справки: с JPEG не рекомендуется ставить качество выше 80%. Обычно — 75% (0.75). Фактор определяет степень "неотличимости глазом" изображения сжатого от конечного и 75% это считается очень много. 100% — скорее приводит к увеличению размера первоначальной картинки, ради создания "неотличимости" включая все артефакты сжатия первоначальной картинки.

**Comment by YuriAndrianov** [comment]
fixed
