### ISSUE TITLE
No way to delete all saved images

### ISSUE THREAD

**Issue by morpheby** [YuriAndrianov/myApp-myAutoBudget#11]
https://github.com/YuriAndrianov/myApp-myAutoBudget/blob/2e9066c36ca5a0e57febb48d36d50c2f854b23b2/myAutoBudget/Helpers/ImageManager.swift#L10

Возможно, стоит предусмотреть возможность удаления всех сохраненных изображений. Иногда необходимо в случае ошибок или проблем с данными очистить содержимое директории приложения — иначе пользователь будет видеть занятое место в приложении но не иметь возможности его очистить.

**Comment by YuriAndrianov** [comment]
added
