### ISSUE TITLE
Remove xcuserdata directories and files from the repository

### ISSUE THREAD

**Issue by morpheby** [YuriAndrianov/myApp-myAutoBudget#2]
Файлы, находящиеся в директориях xcuserdata внутри файлов проектов являются состоянием пользовательского интерфейса в Xcode. Наличие этих файлов будет мешать другим разработчикам и добавляет лишних изменений в проект при каждом коммите.

Лучше всего для этого добавить файл `.gitignore` с указанием там нужных исключений

**Comment by YuriAndrianov** [comment]
fixed
