### ISSUE TITLE
Space in file name

### ISSUE THREAD

**Issue by morpheby** [YuriAndrianov/myApp-myAutoBudget#4]
https://github.com/YuriAndrianov/myApp-myAutoBudget/blob/2e9066c36ca5a0e57febb48d36d50c2f854b23b2/myAutoBudget/Extensions/Date%20%2B%20Extensions.swift#L2

It is not a good practice to use a space in filenames and directory names. Some tools may suddenly break without even proper explanation or cause unintended side effects. It is generally advised to always use paths without spaces for all developer activities, i.e. starting from root `/Users/yourusername/someworkdir/SomeProject/Extensions/Date+Extensions.swift`.

**Comment by YuriAndrianov** [comment]
fixed
