### ISSUE TITLE
RemoveZeros is not doing what it says it does

### ISSUE THREAD

**Issue by morpheby** [YuriAndrianov/myApp-myAutoBudget#6]
https://github.com/YuriAndrianov/myApp-myAutoBudget/blob/2e9066c36ca5a0e57febb48d36d50c2f854b23b2/myAutoBudget/Extensions/Double%20%2B%20removeZerosFromEnd.swift#L11

Метод имеет название, которое не отражает его задачи. Скорее всего, метод более уместен как extension к строке для приведения типа `Double` к форматированной строке

**Comment by YuriAndrianov** [comment]
fixed
