### ISSUE TITLE
Strangely located UI component

### ISSUE THREAD

**Issue by morpheby** [YuriAndrianov/myApp-myAutoBudget#7]
https://github.com/YuriAndrianov/myApp-myAutoBudget/blob/2e9066c36ca5a0e57febb48d36d50c2f854b23b2/myAutoBudget/Extensions/UIButton%20%2B%20createCustomSegmentedControlButton.swift#L11

Не похоже, что компонент находится там, где он должен быть. Для UI компонентов лучше иметь отдельную группу.

**Comment by YuriAndrianov** [comment]
fixed
