### ISSUE TITLE
Current date may be not current

### ISSUE THREAD

**Issue by morpheby** [YuriAndrianov/myApp-myAutoBudget#8]
https://github.com/YuriAndrianov/myApp-myAutoBudget/blob/2e9066c36ca5a0e57febb48d36d50c2f854b23b2/myAutoBudget/Helpers/DateProvider.swift#L12

Текущая дата задается при инициализации класса. Если объект класса был сохранен — дата уже может быть не актуальной

**Comment by YuriAndrianov** [comment]
fixed (removed)
