### ISSUE TITLE
Using a workaround instead of correct format for dates

### ISSUE THREAD

**Issue by morpheby** [YuriAndrianov/myApp-myAutoBudget#9]
https://github.com/YuriAndrianov/myApp-myAutoBudget/blob/2e9066c36ca5a0e57febb48d36d50c2f854b23b2/myAutoBudget/Helpers/DateProvider.swift#L36

Для того, чтобы получить месяц в именительном падеже, следует использовать `"LLLL"` вместо `"MMMM"`.

Чтобы он начинался с большой буквы — `formatter.formattingContext = .standalone`

См. http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns и https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW1

**Comment by YuriAndrianov** [comment]
fixed
